// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Meal struct {
	ID       string      `json:"id"`
	MealType string      `json:"mealType"`
	Food     []*MealFood `json:"food"`
}

type MealFood struct {
	ID       int      `json:"id"`
	Name     string   `json:"name"`
	Size     *float64 `json:"size"`
	Calories *float64 `json:"calories"`
	FoodImg  *string  `json:"foodImg"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
