// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Meal struct {
	ID         string       `json:"id"`
	MealDate   time.Time    `json:"mealDate"`
	MealTypeID int          `json:"mealTypeId"`
	MealType   *MealType    `json:"mealType"`
	FoodEaten  []*FoodEaten `json:"foodEaten"`
}

type MealType struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewFood struct {
	Name     string  `json:"name"`
	Calories int     `json:"calories"`
	FoodImg  *string `json:"foodImg"`
	UnitID   *int    `json:"unitId"`
}

type UnitType struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
